const KEYS = [
  [
    '___\n___\n___'
  ], [
    'o__\n___\n___', '_o_\n___\n___', '___\n_o_\n___'
  ], [
    'ox_\n___\n___',
    'x_o\n___\n___',
    'o__\n_x_\n___',
    '__o\nx__\n___',
    '__x\n___\no__',
    'xo_\n___\n___',
    '_x_\no__\n___',
    '_o_\n_x_\n___',
    '__x\no__\n___',
    '___\nx_o\n___',
    'x__\n_o_\n___',
    '_x_\n_o_\n___'
  ], [
    'oxo\n___\n___', 'ox_\no__\n___', 'ox_\n_o_\n___',
    '_xo\no__\n___', 'o_o\nx__\n___', 'o__\nx_o\n___',
    '_xo\n___\no__', 'xoo\n___\n___', 'o_x\no__\n___',
    'x_o\n_o_\n___', 'x_o\no__\n___', 'o_x\n___\no__',
    'x__\n__o\no__', 'x_o\n___\no__', 'oo_\n_x_\n___',
    'o_o\n_x_\n___', '__o\nox_\n___', '__o\n_x_\no__',
    '_oo\nx__\n___', '__o\nx_o\n___', '__o\nxo_\n___',
    'o__\n__x\no__', '_x_\n__o\no__', '__x\no__\no__',
    '__x\n_o_\no__', '_ox\n___\no__', 'xo_\no__\n___',
    'xo_\n_o_\n___', '_ox\no__\n___', 'x__\no_o\n___',
    '_x_\noo_\n___', '_o_\nx_o\n___', '_x_\no_o\n___',
    '_o_\nox_\n___', '___\noxo\n___', '__x\noo_\n___',
    '_o_\n__o\nx__', '___\nxoo\n___'
  ], [
    'oxo\nx__\n___', 'oxo\n_x_\n___', 'o_x\nx__\no__', 'o__\nx_x\no__',
    'oxx\no__\n___', 'ox_\nox_\n___', '_xo\nx_o\n___', 'oox\nx__\n___',
    'oo_\nx_x\n___', '_xo\n__o\nx__', 'xxo\n_o_\n___', 'ox_\nxo_\n___',
    '_xo\nxo_\n___', 'o_x\nxo_\n___', 'o__\nxox\n___', '__x\nxo_\no__',
    'xxo\no__\n___', 'ox_\nx_o\n___', '_xo\nox_\n___', 'ox_\n__o\nx__',
    '_o_\nx_x\no__', '_ox\nx__\no__', 'oxx\n___\no__', 'o_o\nxx_\n___',
    'ox_\n__x\no__', 'o_o\nx_x\n___', 'o_o\n__x\nx__', 'x__\nx_o\no__',
    'o__\nxxo\n___', '_x_\nx_o\no__', 'o_x\nx_o\n___', '__x\nx_o\no__',
    'xxo\n___\no__', '_xo\n__x\no__', '_xo\n_x_\no__', '_xo\nx__\no__',
    'x_o\n__x\no__', '__o\nx_x\no__', 'xoo\n_x_\n___', 'xoo\nx__\n___',
    'oox\n___\nx__', 'x__\no_x\no__', 'x_x\no__\no__', 'o_x\nox_\n___',
    'x_o\nx_o\n___', 'oo_\n__x\nx__', 'x_o\n__o\nx__', 'x_o\nxo_\n___',
    'o_x\n_o_\nx__', 'x__\n_ox\no__', 'x_x\n_o_\no__', 'x_o\nox_\n___',
    'o_x\n__o\nx__', 'xo_\n__x\no__', 'xox\n___\no__', 'o_x\n_x_\no__',
    'o_x\n__x\no__', 'x_x\n___\no_o', 'x__\n_xo\no__', 'xx_\n__o\no__',
    'x_x\n__o\no__', 'x_o\n_x_\no__', 'o_x\n___\nx_o', '_oo\nxx_\n___',
    '__o\nxxo\n___', '__x\nox_\no__', 'o__\n_xx\no__', '_x_\n_xo\no__',
    '_ox\n_x_\no__', '_x_\no_x\no__', '_xx\no__\no__', '__x\no_x\no__',
    '_x_\n_ox\no__', '_xx\n_o_\no__', '_xx\n__o\no__', 'xox\no__\n___',
    'xo_\nox_\n___', '_ox\nx_o\n___', '_ox\n__o\nx__', 'xox\n_o_\n___',
    'xx_\noo_\n___', '_ox\nxo_\n___', 'x_x\noo_\n___', '__x\nxoo\n___',
    '_ox\n_o_\nx__', 'xo_\nx_o\n___', '_ox\nox_\n___', 'xo_\n__o\nx__',
    '_o_\no_x\nx__', '_ox\no__\nx__', 'x__\no_o\nx__', 'xx_\no_o\n___',
    'x__\noxo\n___', '_x_\no_o\nx__', 'x_x\no_o\n___', '__x\no_o\nx__',
    '_o_\nxox\n___', '_xx\noo_\n___', '_x_\nxoo\n___', '_x_\n_oo\nx__',
    '_o_\nxxo\n___', '_o_\nx_o\nx__', '_x_\nx_o\n_o_', '_x_\noxo\n___',
    '_o_\nx_x\n_o_', '_o_\n_xo\nx__', 'x__\nxoo\n___', 'x__\n_oo\nx__'
  ], [
    'oxo\nxo_\n___', 'oxo\nx_o\n___', 'oxo\nx__\no__', 'ox_\nx_o\no__',
    'oxo\n__x\no__', 'oxo\nox_\n___', 'oxo\n_x_\no__', 'o__\nxxo\no__',
    'oox\nx__\no__', 'o_x\nxo_\no__', 'oxo\n__o\nx__', 'o_x\nx_o\no__',
    'o_x\nx__\no_o', 'oo_\nx_x\no__', 'o__\nxox\no__', 'o_o\nx_x\no__',
    'oxx\noo_\n___', 'xxo\no_o\n___', 'oxx\no__\no__', 'oo_\nx_o\nx__',
    'xxo\n__o\no__', 'ox_\noxo\n___', 'ooo\nxx_\n___', 'oo_\nxxo\n___',
    '_xo\n_xo\no__', '_xo\nxoo\n___', 'ox_\no_x\no__', '_xo\nx_o\n_o_',
    '_xo\nx_o\no__', 'oox\nxo_\n___', 'ox_\no_o\nx__', 'oox\nx_o\n___',
    'xoo\n__x\no__', 'oo_\nxox\n___', 'oo_\nx_x\n_o_', 'ooo\nx_x\n___',
    '_oo\nx_x\no__', '_xo\n_oo\nx__', '_xo\no_o\nx__', 'ooo\n__x\nx__',
    '_oo\no_x\nx__', 'xxo\noo_\n___', 'oxx\n_o_\no__', 'x__\nxoo\no__',
    'xxo\n_o_\no__', 'ox_\nxoo\n___', '_xo\n_ox\no__', 'ox_\n_ox\no__',
    '_x_\nxoo\no__', '_xo\nxo_\no__', 'ox_\n_oo\nx__', 'o_x\nxoo\n___',
    'x_o\n_ox\no__', '_o_\nxox\no__', 'o_o\nxox\n___', '__o\nxox\no__',
    '_ox\nxo_\no__', 'o_o\n_ox\nx__', '__x\nxoo\no__', 'oxx\n__o\no__',
    'xo_\nx_o\no__', 'xxo\no__\no__', 'ox_\nx_o\n_o_', '_xo\no_x\no__',
    'ox_\n_xo\no__', '_o_\nxxo\no__', '_xo\nox_\no__', 'o_x\nx_o\n_o_',
    'x_o\n__x\noo_', 'o_o\nx_x\n_o_', 'o_o\n__x\nxo_', '_ox\nx_o\no__',
    'o_o\nx_o\nx__', 'xxo\n___\no_o', 'o_o\nxxo\n___', 'o_o\n_xx\no__',
    'ox_\n__x\noo_', 'o_o\n__x\nox_', 'o_o\no_x\nx__', 'x_o\nx_o\no__',
    '__o\nxxo\no__', 'x_o\no_x\no__', 'oox\nox_\n___', 'xoo\nox_\n___',
    'oox\n_x_\no__', 'x__\noxo\no__', 'xoo\n_x_\no__', 'xoo\nx_o\n___',
    'xoo\nxo_\n___', 'oox\n__x\no__', 'xx_\no_o\no__', 'oox\no__\nx__',
    'oox\n_o_\nx__', 'oox\n__o\nx__', 'o_x\no_o\nx__', 'oox\n___\nx_o',
    'oo_\no_x\nx__', 'x__\noox\no__', 'xo_\no_x\no__', 'xoo\n__o\nx__',
    'x_x\noo_\no__', 'xox\no__\no__', 'x_x\no__\no_o', 'x_x\no_o\no__',
    'x_o\noxo\n___', 'o_x\nox_\no__', 'oo_\n_xo\nx__', 'x_o\n_xo\no__',
    'x_o\nxoo\n___', 'o_x\no_x\no__', 'x_o\nx_o\n_o_', 'oo_\n_ox\nx__',
    'xo_\n__x\noo_', 'x_o\n_oo\nx__', 'x_o\no_o\nx__', 'x_o\n__o\nx_o',
    'x_x\n__o\noo_', 'o_x\n_ox\no__', 'xx_\n_oo\no__', 'o_x\n_oo\nx__',
    'o_x\n_o_\nx_o', 'xo_\n_ox\no__', 'xox\n_o_\no__', 'x_x\n_o_\no_o',
    'x_x\n_oo\no__', 'o_x\n_xo\no__', 'xo_\n_xo\no__', 'o_x\n__o\nxo_',
    'xox\n___\no_o', 'xox\n__o\no__', 'o_o\n_xo\nx__', 'x_o\n_x_\no_o',
    'o_x\n__x\noo_', '_oo\nxxo\n___', 'oo_\n_xx\no__', '_x_\noxo\no__',
    'o__\noxx\no__', '_o_\noxx\no__', '_oo\n_xo\nx__', '_ox\nox_\no__',
    '__x\noxo\no__', '_ox\n_xo\no__', '_x_\no_x\noo_', '_x_\noox\no__',
    '_oo\nx_o\nx__', '_xx\noo_\no__', '_xx\no_o\no__', '__x\noox\no__',
    '_ox\no_x\no__', '_xx\n_oo\no__', 'xox\noo_\n___', 'xox\no_o\n___',
    'xo_\no_o\nx__', 'xo_\noxo\n___', '_ox\nxoo\n___', '_ox\nx_o\n_o_',
    '_ox\n_oo\nx__', '_ox\no_o\nx__', 'x__\nooo\nx__', 'xo_\nxoo\n___',
    'xx_\nooo\n___', '_x_\nooo\nx__', 'xo_\n_oo\nx__', 'x_x\nooo\n___',
    '_o_\noox\nx__', '_ox\noo_\nx__', '__x\nooo\nx__', 'xx_\no_o\n_o_',
    '_o_\noxo\nx__', 'x_x\no_o\n_o_', '_o_\nxox\n_o_', '_o_\nxoo\nx__',
    '_x_\nxoo\n_o_', '_x_\noxo\n_o_'
  ], [
    'oxo\nxox\n___', 'oxx\nxo_\no__', 'ox_\nxox\no__', 'oxo\n_ox\nx__',
    'oxo\nxxo\n___', 'oxo\nx_o\nx__', 'ox_\nx_x\noo_', 'oxo\no_x\nx__',
    'oxo\nxx_\no__', 'oxo\nx_x\no__', 'oxo\n__x\nx_o', 'ox_\nxxo\no__',
    'oxo\nx_x\n_o_', 'oxx\nx_o\no__', 'oxo\n__x\nxo_', 'oxo\n_xx\no__',
    'oxx\nx__\no_o', 'oxo\n__x\nox_', 'oox\nxx_\no__', 'oo_\nxxx\no__',
    'oxo\n_xo\nx__', 'o_o\nxxx\no__', 'o_x\nxx_\no_o', 'o_x\nxxo\no__',
    'oox\nx_x\no__', 'xoo\n__x\nx_o', 'o_x\nxox\no__', 'x_o\n_ox\nx_o',
    'o_x\nx_x\noo_', 'x_o\no_x\nx_o', 'x_o\nx_x\no_o', 'xxo\nxoo\n___',
    'oxx\noo_\nx__', 'oo_\nxox\nx__', 'xxo\n_oo\nx__', 'xxo\noxo\n___',
    'oxx\no_o\nx__', 'xo_\nx_x\noo_', 'xxo\no_o\nx__', 'oo_\nxxo\nx__',
    'xxo\nx_o\n_o_', 'oox\nx_o\nx__', 'x_x\nx_o\noo_', 'xxo\n_xo\no__',
    'xxo\nx_o\no__', 'oxx\no__\nx_o', 'x_o\nx_x\noo_', 'ox_\noxo\nx__',
    'oo_\nxxx\n_o_', '_xo\noxo\nx__', '_xo\nxxo\n_o_', 'oox\nxxo\n___',
    '_oo\noxx\nx__', '_xo\nxxo\no__', 'xoo\n_xx\no__', '_oo\nxxx\no__',
    'ox_\noox\nx__', '_x_\nxox\noo_', '_xo\nxoo\nx__', 'ox_\no_x\nxo_',
    '_xx\nx_o\noo_', 'xoo\n__x\nox_', '_xo\nx_x\noo_', 'xoo\nxox\n___',
    'xoo\n_ox\nx__', 'xoo\nx_x\n_o_', 'xoo\n__x\nxo_', 'xoo\no_x\nx__',
    'xoo\nx_x\no__', '_oo\nxox\nx__', '_ox\nx_x\noo_', 'oxx\nxoo\n___',
    'oxx\n_oo\nx__', 'xo_\nxox\no__', 'xox\nxo_\no__', 'oxx\n_ox\no__',
    'o_o\nxox\nx__', 'x_x\nxo_\no_o', 'ox_\nxoo\nx__', 'xx_\nxoo\no__',
    'o_x\nxoo\nx__', 'x_x\nxoo\no__', 'ox_\nxox\n_o_', '_xo\noox\nx__',
    'o_o\nxox\n_x_', 'o_x\n_ox\nox_', 'ox_\n_ox\nxo_', '_xx\nxoo\no__',
    'x_o\nxox\n_o_', 'x_o\n_ox\nxo_', 'x_o\noox\nx__', '_ox\nxox\no__',
    'oxx\n_xo\no__', 'o_o\nx_x\nxo_', 'xox\nx__\no_o', 'oxx\nx_o\n_o_',
    'xo_\nxxo\no__', 'oxx\n__o\nxo_', 'xox\nx_o\no__', 'xxo\no_x\no__',
    'xxo\nox_\no__', 'oxx\n__o\nx_o', 'ox_\nxxo\n_o_', '_xo\no_x\nxo_',
    '_xo\noxx\no__', 'xxo\n__x\noo_', 'o_o\nxxx\n_o_', 'o_o\n_xx\nxo_',
    'o_x\nxxo\n_o_', '_ox\nxxo\no__', 'x_o\n_xx\noo_', 'x_o\no_x\nxo_',
    'o_o\nxxo\nx__', 'oxx\n__x\noo_', 'x_x\nx_o\no_o', 'xxo\n_x_\no_o',
    'xxo\nx__\no_o', 'ox_\n_xx\noo_', 'o_o\noxx\nx__', 'o_o\n_xx\nox_',
    'oox\n__x\nox_', 'x_o\nxxo\no__', 'o_x\nx_o\nx_o', 'x_o\noxx\no__',
    'xoo\nxxo\n___', 'oox\nox_\nx__', 'oo_\noxx\nx__', 'xoo\n_xo\nx__',
    'oox\n_xo\nx__', 'xo_\noxx\no__', 'xox\nox_\no__', 'oox\n_xx\no__',
    'x_x\nox_\no_o', 'xx_\noxo\no__', 'o_x\noxo\nx__', 'x_x\noxo\no__',
    'oox\n_x_\nx_o', 'oox\no_x\nx__', 'xx_\no_x\noo_', 'xoo\nx_o\nx__',
    'oox\n_ox\nx__', 'xx_\noox\no__', 'xxx\noo_\no__', 'xxx\no__\no_o',
    'oox\n__x\nxo_', 'xxx\no_o\no__', 'x_x\n__o\nxoo', 'o_x\noox\nx__',
    'x_x\n_oo\nx_o', 'o_x\no_x\nxo_', 'xox\n__o\nx_o', 'x_x\no_o\nx_o',
    'x_x\no_x\noo_', 'x_x\noox\no__', 'xox\no_x\no__', 'xo_\n_xx\noo_',
    'x_o\noxo\nx__', 'x_o\nxxo\n_o_', 'x_x\n_xo\noo_', 'xx_\n_ox\noo_',
    'x_o\nxoo\nx__', 'xxx\n__o\noo_', 'x_x\n_ox\noo_', 'xox\n__x\noo_',
    'xxx\n_o_\no_o', 'o_x\n_ox\nxo_', 'xxx\n_oo\no__', 'xox\n_o_\nx_o',
    'xox\n_ox\no__', 'xox\n_x_\no_o', 'o_x\n_xo\nxo_', 'xox\n_xo\no__',
    'xox\no__\nx_o', 'o_x\n_xx\noo_', '_x_\noxx\noo_', '_oo\nxxo\nx__',
    '_xx\noxo\no__', '_ox\noxx\no__', '_xx\no_x\noo_', '_xx\noox\no__',
    'xox\nxoo\n___', 'xox\noo_\nx__', 'xo_\noox\nx__', 'xox\n_oo\nx__',
    'xox\noxo\n___', 'xox\no_o\nx__', 'xo_\no_x\nxo_', 'xo_\noxo\nx__',
    'xox\nx_o\n_o_', 'xox\n__o\nxo_', '_ox\nxxo\n_o_', '_ox\noxo\nx__',
    '_x_\noox\nxo_', '_ox\nxoo\nx__', '_xx\no_o\nxo_', 'xo_\nxoo\nx__',
    '_xx\nxoo\n_o_', '_ox\noox\nx__', 'x_x\nxoo\n_o_', 'x_x\n_oo\nxo_',
    'xx_\noxo\n_o_', 'xxx\no_o\n_o_', 'x_x\noxo\n_o_', 'xx_\nxoo\n_o_'
  ], [
    'oxo\nxox\no__', 'oxo\nxox\n_o_', 'oxo\nxoo\nx__', 'oxx\nxoo\no__',
    'oxx\nxo_\no_o', 'ox_\nxox\noo_', 'oxo\n_ox\nox_', 'oxo\noox\nx__',
    'oxo\n_ox\nx_o', 'oxo\n_ox\nxo_', 'oxo\nxxo\no__', 'oxo\nxxo\n_o_',
    'oxo\noxx\no__', 'oxx\nx_o\noo_', 'oxo\nx_o\nx_o', 'oxo\nx_x\noo_',
    'oxo\no_x\nox_', 'oxo\no_x\nx_o', 'oxo\no_x\nxo_', 'oxo\nxx_\no_o',
    'oxo\nx_x\no_o', 'oxo\n_xx\noo_', 'oxx\nx_o\no_o', 'oxo\noxo\nx__',
    'oox\nxxo\no__', 'oox\nxx_\no_o', 'oxo\n_xo\nx_o', 'o_x\nxxo\noo_',
    'o_x\nxxo\no_o', 'oox\nxox\no__', 'oox\nx_x\noo_', 'xoo\nx_x\no_o',
    'xoo\n_ox\nx_o', 'xoo\n__x\nxoo', 'xoo\no_x\nx_o', 'o_x\nxox\noo_',
    'x_o\nxox\no_o', 'x_o\noox\nx_o', 'ooo\nx_x\nx_o', 'oxx\noox\no__',
    'xxo\nxoo\n_o_', 'xxo\nxoo\no__', 'oxx\nooo\nx__', 'oox\nxoo\nx__',
    'oxx\noo_\nx_o', 'xo_\nxox\noo_', 'ooo\nxox\nx__', 'x_o\nxox\noo_',
    'xxo\nooo\nx__', 'xxo\n_oo\nx_o', 'x_x\nxoo\noo_', 'oxx\noxo\no__',
    'xxo\noxo\n_o_', 'xxo\noxo\no__', 'oxx\no_o\nxo_', 'oxx\no_o\nx_o',
    'ooo\nx_x\nxo_', 'xoo\nx_x\noo_', 'xxo\no_o\nx_o', 'xox\nx_o\noo_',
    'ooo\nxxo\nx__', 'xxo\n_xo\noo_', 'oxx\no_x\noo_', 'xxo\nx_o\noo_',
    'oox\nx_o\nx_o', 'x_x\nx_o\nooo', 'oxx\nox_\no_o', 'xxo\nx_o\no_o',
    'oox\nxxo\n_o_', 'xoo\n_xx\noo_', 'ooo\n_xx\nxo_', '_ox\nxxo\noo_',
    'ox_\noxx\noo_', '_xo\nxxo\noo_', 'xoo\noxx\no__', 'ooo\noxx\nx__',
    'ooo\n_xx\nox_', 'ox_\noox\nxo_', 'xoo\n_ox\nox_', 'ooo\nxox\n_x_',
    '_xo\nxox\noo_', 'o_x\noox\nox_', '_xx\nxoo\noo_', 'xoo\no_x\nox_',
    'oox\no_x\nox_', 'xoo\nxox\n_o_', 'xoo\nxox\no__', 'xoo\n_ox\nxo_',
    'xoo\noox\nx__', 'xoo\no_x\nxo_', '_ox\nxox\noo_', 'oxx\nxoo\n_o_',
    'xxo\noox\no__', 'oxx\n_oo\nxo_', 'oxx\n_oo\nx_o', 'o_o\nxox\nxo_',
    'xox\nxo_\no_o', 'xox\nxoo\no__', 'oxx\n_ox\noo_', 'xxo\nxo_\no_o',
    'x_x\nxoo\no_o', 'xxo\n_ox\noo_', 'o_x\nxoo\nx_o', '_xo\noox\nxo_',
    'oox\n_ox\nox_', 'x_o\noox\nxo_', 'oxx\n_xo\noo_', 'xxo\nox_\no_o',
    'xox\nx_o\no_o', 'xxo\no_x\noo_', 'xoo\nxxo\no__', 'oox\no_x\nx_o',
    '_xo\noxx\noo_', 'o_o\noxx\nxo_', 'x_o\noxx\noo_', 'x_o\nxxo\no_o',
    'oox\noxx\no__', 'xoo\nxxo\n_o_', 'xo_\noxx\noo_', 'xoo\noxo\nx__',
    'xoo\n_xo\nx_o', 'x_x\noxo\noo_', 'xox\nox_\no_o', 'xox\noxo\no__',
    'oox\n_xx\noo_', 'x_x\noxo\no_o', 'oox\noox\nx__', 'oox\no_x\nxo_',
    'xx_\noox\noo_', 'oox\n_ox\nxo_', 'x_x\n_oo\nxoo', 'xox\n__o\nxoo',
    'o_x\noox\nxo_', 'xox\n_oo\nx_o', 'x_x\nooo\nx_o', 'xox\no_o\nx_o',
    'x_x\noox\noo_', 'xox\no_x\noo_', 'xox\noox\no__', 'x_o\noxo\nx_o',
    'xox\n_xo\noo_', 'o_x\noxx\noo_', 'xox\n_ox\noo_', 'xox\noo_\nx_o',
    '_xx\noxo\noo_', '_xx\noox\noo_', 'xox\nxoo\n_o_', 'xox\nooo\nx__',
    'xo_\noox\nxo_', 'xox\n_oo\nxo_', 'xox\noxo\n_o_', 'xox\no_o\nxo_',
    '_xx\nooo\nxo_'
  ], [
    'oxo\nxox\nxo_', 'oxx\nxox\noo_', 'xxo\n_ox\nxoo',
    'xxo\noox\nx_o', 'oox\nxox\nox_', 'oxo\nxxx\noo_',
    'oxo\noxx\nx_o', 'oxx\nxxo\noo_', 'oxo\noxx\nxo_',
    'xxo\no_x\nxoo', 'oxo\nx_x\nxoo', 'oxo\nxxx\no_o',
    'oxo\nx_x\noxo', 'oxx\nxxo\no_o', 'oox\nxxx\noo_',
    'xoo\n_xx\nxoo', 'xoo\noxx\nx_o', 'xoo\nxxx\no_o',
    'xoo\nxox\nx_o', 'xoo\nx_x\nxoo', 'oxx\noox\nxo_',
    'xxx\nxoo\noo_', 'x_x\noox\nxoo', 'oxx\noxo\nxo_',
    'xox\nxxo\noo_', 'oxx\noxo\nx_o', 'xoo\nxxx\noo_',
    'xox\no_x\nxoo', 'oox\nx_x\nxoo', 'xxo\nxxo\noo_',
    'oox\nxxo\nx_o', 'oxx\no_x\nxoo', 'xoo\noxx\nxo_',
    'xoo\noxx\nox_', 'xox\noox\nox_', 'oxx\nxoo\nxo_',
    'xxo\noox\nxo_', 'xox\noox\nx_o', 'xox\nxox\no_o',
    'xxx\nxoo\no_o', 'xox\nxxo\no_o', 'xxo\noxx\noo_',
    'oxx\nx_o\nxoo', 'oox\noxx\nx_o', 'oox\noxx\nxo_',
    'xxx\noxo\noo_', 'xox\noxx\noo_', 'xox\n_xo\nxoo',
    'xox\noxo\nx_o', 'xxx\noxo\no_o', 'oox\noox\nxx_',
    'xxx\n_oo\nxoo', 'xxx\no_o\nxoo', 'xxx\noox\noo_',
    'xox\nxoo\nx_o', 'xox\noxo\nxo_', 'xox\no_o\nxox'
  ], [
    'oxo\nxox\nxoo', 'xxo\nxox\nooo',
    'xxo\noox\nxoo', 'oxo\noxx\nxoo',
    'oxx\nxxo\nooo', 'oxo\nxox\noxo',
    'xoo\noxx\nxoo', 'oxx\noox\nxoo',
    'xox\noox\nxoo', 'xox\nxxo\nooo',
    'oox\nxox\nxoo', 'xxo\nxxo\nooo',
    'oxx\nxoo\nxoo', 'xox\nxox\nooo',
    'xox\nooo\nxox'
  ]
]

module.exports = KEYS;
